services:
  backend:
    build: .
    container_name: "backend-express"
    ports:
      - "3333:3333"
    depends_on:
      - "mongo"
  
  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    volumes:
      - "mongodb:/data/db"
    ports:
      - "27017:27017"
volumes:
  mongodb:

